import Link from 'next/link';
import { buildMetadata, breadcrumbJsonLd, SITE_NAME } from '@/lib/seo';
import JsonLd from '@/components/ui/JsonLd';

export const metadata = buildMetadata({
  title: 'Terms of Service - Igris Radar',
  description:
    'The terms governing your use of Igris Radar\'s security, SEO, AEO, GEO, brand visibility, and site health audit platform.',
  path: '/landing/terms',
});

const LAST_UPDATED = 'July 7, 2026';

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of terms',
    body: (
      <>
        <p>
          These Terms of Service ("Terms") form a binding agreement between you ("you" or "your")
          and {SITE_NAME} ("{SITE_NAME}", "we", "us", or "our"), governing your access to and use of
          the {SITE_NAME} website, dashboard, and audit tools (collectively, the "Service").
        </p>
        <p>
          By creating an account, running a scan, or otherwise using the Service, you agree to be
          bound by these Terms and our <Link href="/landing/privacy" className="text-primary hover:underline">Privacy Policy</Link>.
          If you do not agree, do not use the Service.
        </p>
      </>
    ),
  },
  {
    id: 'accounts',
    title: '2. Accounts',
    body: (
      <>
        <p>
          You must provide accurate information when creating an account and keep your login
          credentials confidential. You are responsible for all activity that occurs under your
          account. Notify us immediately at{' '}
          <a href="mailto:support@igrisecurity.com" className="text-primary hover:underline">support@igrisecurity.com</a>{' '}
          if you suspect unauthorized use.
        </p>
        <p>
          You must be at least 18 years old, or the age of legal majority in your jurisdiction, to
          use the Service.
        </p>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    title: '3. Acceptable use',
    body: (
      <>
        <p>You agree to use the Service only to audit domains you own, operate, or are authorized to assess. You will not:</p>
        <ul className="list-disc pl-6 space-y-1.5 marker:text-primary">
          <li>Run scans against third-party sites without authorization from the site owner.</li>
          <li>Use the Service to probe, attack, or degrade the availability of any system.</li>
          <li>Attempt to bypass rate limits, plan limits, or access controls.</li>
          <li>Reverse-engineer, scrape, or resell the Service or its underlying audit engines.</li>
          <li>Upload content that is unlawful, infringing, or that you lack the rights to submit.</li>
          <li>Use the Service to build a directly competing product.</li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate this section, with or without notice,
          at our discretion.
        </p>
      </>
    ),
  },
  {
    id: 'scanning',
    title: '4. Scanning and audit results',
    body: (
      <>
        <p>
          {SITE_NAME}'s audits (security, SEO, AEO, GEO, brand visibility, and site health) analyze
          publicly reachable pages and, where applicable, query third-party AI engines and search
          APIs. Scores, findings, and remediation guidance are provided on an informational basis
          and represent our engines' assessment at the time of the scan - they are not a guarantee
          of security, search ranking, or AI citation outcomes.
        </p>
        <p>
          Fix prompts generated by the Service are suggestions intended for use with your own AI
          coding assistant or developers. You are responsible for reviewing and testing any change
          before deploying it to a live system.
        </p>
      </>
    ),
  },
  {
    id: 'plans',
    title: '5. Plans, billing, and cancellation',
    body: (
      <>
        <p>
          The Service is offered under a free plan with limited monthly scans and paid plans with
          higher limits and additional features, as described on our{' '}
          <Link href="/landing#pricing" className="text-primary hover:underline">pricing page</Link>.
          Paid subscriptions are billed in advance on a recurring basis until cancelled.
        </p>
        <p>
          You may cancel a paid plan at any time from Settings; cancellation takes effect at the end
          of the current billing period. Fees already paid are non-refundable except where required
          by law. We may change plan pricing or limits with notice posted on this page or sent to
          your account email; continued use after a change takes effect constitutes acceptance.
        </p>
      </>
    ),
  },
  {
    id: 'ip',
    title: '6. Intellectual property',
    body: (
      <p>
        The Service, including its audit engines, scoring methodology, UI, and branding, is owned by
        {' '}{SITE_NAME} and protected by intellectual property laws. We grant you a limited,
        non-exclusive, non-transferable license to use the Service for your own business purposes
        during your subscription. You retain ownership of any content and URLs you submit for
        scanning.
      </p>
    ),
  },
  {
    id: 'disclaimer',
    title: '7. Disclaimers',
    body: (
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS
        OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. We do not warrant that audits will detect every vulnerability or ranking
        factor, that the Service will be uninterrupted or error-free, or that third-party AI engines
        queried by the Service will remain available or accurate.
      </p>
    ),
  },
  {
    id: 'liability',
    title: '8. Limitation of liability',
    body: (
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, {SITE_NAME.toUpperCase()} SHALL NOT BE LIABLE FOR
        ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
        PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR
        ANY CLAIM ARISING FROM THESE TERMS WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS
        PRECEDING THE CLAIM.
      </p>
    ),
  },
  {
    id: 'termination',
    title: '9. Termination',
    body: (
      <p>
        You may stop using the Service and delete your account at any time from Settings. We may
        suspend or terminate your access if you violate these Terms, fail to pay applicable fees, or
        if required by law. Sections that by their nature should survive termination (including
        Intellectual Property, Disclaimers, and Limitation of Liability) will survive.
      </p>
    ),
  },
  {
    id: 'changes',
    title: '10. Changes to these Terms',
    body: (
      <p>
        We may update these Terms from time to time. Material changes will be reflected by updating
        the "Last updated" date below, and where appropriate, by notifying you via email or an
        in-product notice. Continued use of the Service after changes take effect constitutes
        acceptance of the revised Terms.
      </p>
    ),
  },
  {
    id: 'contact',
    title: '11. Contact',
    body: (
      <p>
        Questions about these Terms can be sent to{' '}
        <a href="mailto:support@igrisecurity.com" className="text-primary hover:underline">support@igrisecurity.com</a>{' '}
        or via our <Link href="/landing/contact" className="text-primary hover:underline">contact page</Link>.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div>
      <JsonLd data={breadcrumbJsonLd([
        { name: 'Home', path: '/landing' },
        { name: 'Terms of Service', path: '/landing/terms' },
      ])} />

      <section className="relative overflow-hidden">
        <div
          className="absolute inset-0 pointer-events-none opacity-60"
          style={{ background: 'radial-gradient(ellipse 60% 50% at 50% -10%, hsl(var(--accent)) 0%, transparent 70%)' }}
        />
        <div className="max-w-3xl mx-auto px-4 sm:px-6 pt-20 pb-10 relative">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-primary/25 bg-primary/5 text-primary text-xs font-semibold uppercase tracking-wider mb-6">
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight leading-[1.1]">Terms of Service</h1>
          <p className="mt-4 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>
      </section>

      <section className="max-w-3xl mx-auto px-4 sm:px-6 pb-24">
        <div className="space-y-10">
          {SECTIONS.map(({ id, title, body }) => (
            <div key={id} id={id} className="scroll-mt-24">
              <h2 className="text-xl md:text-2xl font-bold tracking-tight">{title}</h2>
              <div className="mt-3 space-y-3 text-muted-foreground leading-relaxed">{body}</div>
            </div>
          ))}
        </div>

        <div className="mt-14 pt-8 border-t border-border">
          <p className="text-sm text-muted-foreground">
            See also our <Link href="/landing/privacy" className="text-primary hover:underline">Privacy Policy</Link>.
          </p>
        </div>
      </section>
    </div>
  );
}
