/**
 * Scanner identity accents - single source of truth for per-tool colors.
 * Tailwind requires full class names in source, so each scanner maps to
 * a set of pre-built class strings (never build class names dynamically).
 */
import {
  Shield,
  Search,
  Sparkles,
  Bot,
  Target,
  Activity,
  Smartphone,
} from 'lucide-react';

export const SCANNERS = {
  security: {
    key: 'security',
    label: 'Security Scan',
    route: '/security-scan',
    icon: Shield,
    description: 'Headers, secrets & exposure',
    text: 'text-scanner-security',
    bg: 'bg-scanner-security',
    bgSoft: 'bg-scanner-security/10',
    border: 'border-scanner-security/30',
    borderHover: 'hover:border-scanner-security/60',
    bgSoftHover: 'hover:bg-scanner-security/10',
    ring: 'hsl(var(--accent-security))',
  },
  seo: {
    key: 'seo',
    label: 'SEO Audit',
    route: '/seo-audit',
    icon: Search,
    description: 'Search visibility',
    text: 'text-scanner-seo',
    bg: 'bg-scanner-seo',
    bgSoft: 'bg-scanner-seo/10',
    border: 'border-scanner-seo/30',
    borderHover: 'hover:border-scanner-seo/60',
    bgSoftHover: 'hover:bg-scanner-seo/10',
    ring: 'hsl(var(--accent-seo))',
  },
  aeo: {
    key: 'aeo',
    label: 'AEO Audit',
    route: '/aeo-audit',
    icon: Sparkles,
    description: 'AI answer engine readiness',
    text: 'text-scanner-aeo',
    bg: 'bg-scanner-aeo',
    bgSoft: 'bg-scanner-aeo/10',
    border: 'border-scanner-aeo/30',
    borderHover: 'hover:border-scanner-aeo/60',
    bgSoftHover: 'hover:bg-scanner-aeo/10',
    ring: 'hsl(var(--accent-aeo))',
  },
  geo: {
    key: 'geo',
    label: 'GEO Audit',
    route: '/geo-audit',
    icon: Bot,
    description: 'Generative engine optimization',
    text: 'text-scanner-geo',
    bg: 'bg-scanner-geo',
    bgSoft: 'bg-scanner-geo/10',
    border: 'border-scanner-geo/30',
    borderHover: 'hover:border-scanner-geo/60',
    bgSoftHover: 'hover:bg-scanner-geo/10',
    ring: 'hsl(var(--accent-geo))',
  },
  aso: {
    key: 'aso',
    label: 'ASO Audit',
    route: '/aso-audit',
    icon: Smartphone,
    description: 'App Store listing optimization',
    text: 'text-scanner-aso',
    bg: 'bg-scanner-aso',
    bgSoft: 'bg-scanner-aso/10',
    border: 'border-scanner-aso/30',
    borderHover: 'hover:border-scanner-aso/60',
    bgSoftHover: 'hover:bg-scanner-aso/10',
    ring: 'hsl(var(--accent-aso))',
  },
  brand: {
    key: 'brand',
    label: 'Brand Visibility',
    route: '/brand-visibility',
    icon: Target,
    description: 'AI brand mention tracking',
    text: 'text-scanner-brand',
    bg: 'bg-scanner-brand',
    bgSoft: 'bg-scanner-brand/10',
    border: 'border-scanner-brand/30',
    borderHover: 'hover:border-scanner-brand/60',
    bgSoftHover: 'hover:bg-scanner-brand/10',
    ring: 'hsl(var(--accent-brand))',
  },
  health: {
    key: 'health',
    label: 'Site Health',
    route: '/site-health',
    icon: Activity,
    description: 'Speed & accessibility',
    text: 'text-scanner-health',
    bg: 'bg-scanner-health',
    bgSoft: 'bg-scanner-health/10',
    border: 'border-scanner-health/30',
    borderHover: 'hover:border-scanner-health/60',
    bgSoftHover: 'hover:bg-scanner-health/10',
    ring: 'hsl(var(--accent-health))',
  },
};

/** Severity → static class/icon-color map (fixes dynamic `bg-${color}-500` bug) */
export const SEVERITY_STYLES = {
  critical: { bar: 'bg-severity-critical', text: 'text-severity-critical', label: 'Critical' },
  high: { bar: 'bg-severity-high', text: 'text-severity-high', label: 'High' },
  medium: { bar: 'bg-severity-medium', text: 'text-severity-medium', label: 'Medium' },
  low: { bar: 'bg-severity-low', text: 'text-severity-low', label: 'Low' },
  passed: { bar: 'bg-success', text: 'text-success', label: 'Passed' },
};
