/**
 * Top 50 Domain Security Benchmark Data.
 * Powering the public /reports directory and /reports/[domain] detail pages.
 */

export const DOMAIN_CATEGORIES = [
  { id: 'all', name: 'All Domains' },
  { id: 'big-tech', name: 'Big Tech' },
  { id: 'fintech', name: 'Fintech & Banking' },
  { id: 'saas', name: 'SaaS & Productivity' },
  { id: 'devtools', name: 'DevTools & Cloud' },
  { id: 'ecommerce', name: 'E-Commerce' },
  { id: 'media', name: 'Media & Social' },
  { id: 'ai', name: 'AI & Research' },
];

export const TOP_DOMAINS = [
  // 1. Big Tech
  {
    domain: 'google.com',
    slug: 'google-com',
    name: 'Google',
    category: 'big-tech',
    score: 58,
    grade: 'C',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 14, warning: 6, failed: 4, total: 24 },
    categoryScores: { tls: 95, headers: 45, cookies: 80, dns: 90, secrets: 100, attackSurface: 70 },
    highlights: ['HTTPS & TLS 1.3 enforced', 'Missing strict CSP header', 'Wildcard CORS policies on sub-APIs'],
  },
  {
    domain: 'apple.com',
    slug: 'apple-com',
    name: 'Apple',
    category: 'big-tech',
    score: 84,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 98, headers: 82, cookies: 90, dns: 95, secrets: 100, attackSurface: 85 },
    highlights: ['HSTS Preload enabled', 'Strict Permissions-Policy', 'DKIM & SPF verified'],
  },
  {
    domain: 'microsoft.com',
    slug: 'microsoft-com',
    name: 'Microsoft',
    category: 'big-tech',
    score: 79,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 18, warning: 4, failed: 2, total: 24 },
    categoryScores: { tls: 92, headers: 75, cookies: 85, dns: 90, secrets: 100, attackSurface: 78 },
    highlights: ['Comprehensive DNSSEC', 'HSTS active across subdomains', 'Legacy cookies on older sub-endpoints'],
  },
  {
    domain: 'amazon.com',
    slug: 'amazon-com',
    name: 'Amazon',
    category: 'big-tech',
    score: 74,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 17, warning: 5, failed: 2, total: 24 },
    categoryScores: { tls: 94, headers: 68, cookies: 82, dns: 88, secrets: 100, attackSurface: 72 },
    highlights: ['CloudFront WAF edge protection', 'Permissive CSP due to retail ad integrations', 'DMARC p=reject enforced'],
  },
  {
    domain: 'meta.com',
    slug: 'meta-com',
    name: 'Meta',
    category: 'big-tech',
    score: 88,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 2, failed: 1, total: 24 },
    categoryScores: { tls: 98, headers: 90, cookies: 92, dns: 96, secrets: 100, attackSurface: 88 },
    highlights: ['Strict CSP with nonces', 'MTA-STS mail transport security', 'DNSSEC validating resolver'],
  },
  {
    domain: 'netflix.com',
    slug: 'netflix-com',
    name: 'Netflix',
    category: 'big-tech',
    score: 86,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 86, cookies: 90, dns: 92, secrets: 100, attackSurface: 84 },
    highlights: ['HSTS Preload registered', 'Secure cookie prefixes used', 'CORS origin isolation'],
  },
  {
    domain: 'cloudflare.com',
    slug: 'cloudflare-com',
    name: 'Cloudflare',
    category: 'big-tech',
    score: 96,
    grade: 'A+',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 23, warning: 1, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 98, cookies: 98, dns: 100, secrets: 100, attackSurface: 95 },
    highlights: ['Flawless TLS 1.3 & 0-RTT', 'Strict CSP + COOP/COEP isolation', 'Full DNSSEC & CAA records'],
  },
  {
    domain: 'adobe.com',
    slug: 'adobe-com',
    name: 'Adobe',
    category: 'big-tech',
    score: 72,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 16, warning: 6, failed: 2, total: 24 },
    categoryScores: { tls: 90, headers: 65, cookies: 80, dns: 85, secrets: 100, attackSurface: 70 },
    highlights: ['Modern TLS 1.3 ciphers', 'Missing frame-ancestors in CSP', 'DMARC p=quarantine'],
  },

  // 2. Fintech & Banking
  {
    domain: 'stripe.com',
    slug: 'stripe-com',
    name: 'Stripe',
    category: 'fintech',
    score: 94,
    grade: 'A+',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 23, warning: 1, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 95, cookies: 96, dns: 98, secrets: 100, attackSurface: 92 },
    highlights: ['Zero-trust HSTS Preload', 'Strict CSP with strict-dynamic nonces', 'Hardened __Host- cookie prefixes'],
  },
  {
    domain: 'paypal.com',
    slug: 'paypal-com',
    name: 'PayPal',
    category: 'fintech',
    score: 83,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 95, headers: 80, cookies: 88, dns: 92, secrets: 100, attackSurface: 82 },
    highlights: ['PCI DSS compliant header suite', 'DMARC p=reject active', 'X-Frame-Options: DENY'],
  },
  {
    domain: 'wise.com',
    slug: 'wise-com',
    name: 'Wise',
    category: 'fintech',
    score: 91,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 94, dns: 95, secrets: 100, attackSurface: 90 },
    highlights: ['Strict CORS whitelisting', 'Permissions-Policy fully defined', 'Subresource Integrity hashes'],
  },
  {
    domain: 'revolut.com',
    slug: 'revolut-com',
    name: 'Revolut',
    category: 'fintech',
    score: 89,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 86 },
    highlights: ['HSTS 2-year max-age', 'Anti-CSRF SameSite=Strict cookies', 'BIMI verified email records'],
  },
  {
    domain: 'square.com',
    slug: 'square-com',
    name: 'Square (Block)',
    category: 'fintech',
    score: 92,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 94, cookies: 95, dns: 96, secrets: 100, attackSurface: 88 },
    highlights: ['DNSSEC validated', 'Strict Content Security Policy', 'TLS 1.3 forward secrecy'],
  },
  {
    domain: 'plaid.com',
    slug: 'plaid-com',
    name: 'Plaid',
    category: 'fintech',
    score: 93,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 92, cookies: 96, dns: 96, secrets: 100, attackSurface: 90 },
    highlights: ['SOC 2 Type II controls verified', 'CAA records restrict CAs', 'Full HSTS preload suite'],
  },
  {
    domain: 'coinbase.com',
    slug: 'coinbase-com',
    name: 'Coinbase',
    category: 'fintech',
    score: 87,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 4, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 86, cookies: 90, dns: 94, secrets: 100, attackSurface: 85 },
    highlights: ['Hardware 2FA protection', 'Strict frame isolation', 'OCSP stapling configured'],
  },
  {
    domain: 'chase.com',
    slug: 'chase-com',
    name: 'Chase Bank',
    category: 'fintech',
    score: 82,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 78, cookies: 88, dns: 92, secrets: 100, attackSurface: 80 },
    highlights: ['Financial-grade cipher suites', 'Akamai Edge WAF security', 'Complex legacy CSP rules'],
  },

  // 3. SaaS & Productivity
  {
    domain: 'notion.so',
    slug: 'notion-so',
    name: 'Notion',
    category: 'saas',
    score: 85,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 84, cookies: 90, dns: 92, secrets: 100, attackSurface: 84 },
    highlights: ['HSTS with subdomains', 'Strict SameSite session cookies', 'Cloudflare DDoS protection'],
  },
  {
    domain: 'slack.com',
    slug: 'slack-com',
    name: 'Slack',
    category: 'saas',
    score: 90,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 90, cookies: 92, dns: 95, secrets: 100, attackSurface: 88 },
    highlights: ['Strict-Transport-Security preload', 'Granular Permissions-Policy', 'Automated token rotation'],
  },
  {
    domain: 'zoom.us',
    slug: 'zoom-us',
    name: 'Zoom',
    category: 'saas',
    score: 81,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 94, headers: 78, cookies: 86, dns: 90, secrets: 100, attackSurface: 80 },
    highlights: ['End-to-end encryption transport', 'Strict Cookie prefixes', 'Subdomain takeover protection'],
  },
  {
    domain: 'figma.com',
    slug: 'figma-com',
    name: 'Figma',
    category: 'saas',
    score: 91,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 94, dns: 95, secrets: 100, attackSurface: 90 },
    highlights: ['Wasm memory isolation', 'Strict CSP script-src nonces', 'Automated dependency CVE scanning'],
  },
  {
    domain: 'canva.com',
    slug: 'canva-com',
    name: 'Canva',
    category: 'saas',
    score: 86,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 85, cookies: 90, dns: 92, secrets: 100, attackSurface: 85 },
    highlights: ['Cloudflare WAF integration', 'Subresource Integrity on CDN assets', 'Secure cookie flags'],
  },
  {
    domain: 'airtable.com',
    slug: 'airtable-com',
    name: 'Airtable',
    category: 'saas',
    score: 88,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 87 },
    highlights: ['DMARC p=reject enforced', 'Cross-origin isolation policies', '0 exposed sensitive files'],
  },
  {
    domain: 'dropbox.com',
    slug: 'dropbox-com',
    name: 'Dropbox',
    category: 'saas',
    score: 92,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 94, cookies: 95, dns: 96, secrets: 100, attackSurface: 90 },
    highlights: ['Pioneer in CSP implementation', 'HSTS preloaded globally', 'Zero open admin ports'],
  },
  {
    domain: 'asana.com',
    slug: 'asana-com',
    name: 'Asana',
    category: 'saas',
    score: 87,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 4, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 86, cookies: 90, dns: 94, secrets: 100, attackSurface: 86 },
    highlights: ['Modern TLS 1.3', 'Comprehensive DMARC/SPF authentication', 'Clean public attack surface'],
  },
  {
    domain: 'hubspot.com',
    slug: 'hubspot-com',
    name: 'HubSpot',
    category: 'saas',
    score: 84,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 94, headers: 82, cookies: 88, dns: 92, secrets: 100, attackSurface: 82 },
    highlights: ['Cloudflare Enterprise WAF', 'Permissions-Policy configured', 'Strict HttpOnly cookie flags'],
  },

  // 4. DevTools & Cloud Platforms
  {
    domain: 'github.com',
    slug: 'github-com',
    name: 'GitHub',
    category: 'devtools',
    score: 95,
    grade: 'A+',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 23, warning: 1, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 96, cookies: 96, dns: 98, secrets: 100, attackSurface: 94 },
    highlights: ['Gold standard CSP policy', 'HSTS preloaded 2-year duration', 'Zero information disclosure headers'],
  },
  {
    domain: 'gitlab.com',
    slug: 'gitlab-com',
    name: 'GitLab',
    category: 'devtools',
    score: 91,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 94, dns: 95, secrets: 100, attackSurface: 90 },
    highlights: ['Strict security headers', 'DMARC p=reject', 'Subdomain takeover monitoring'],
  },
  {
    domain: 'vercel.com',
    slug: 'vercel-com',
    name: 'Vercel',
    category: 'devtools',
    score: 96,
    grade: 'A+',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 23, warning: 1, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 98, cookies: 98, dns: 100, secrets: 100, attackSurface: 95 },
    highlights: ['Edge network security', 'Automatic TLS 1.3 & HTTP/3', 'Strict CSP & Next.js headers'],
  },
  {
    domain: 'netlify.com',
    slug: 'netlify-com',
    name: 'Netlify',
    category: 'devtools',
    score: 93,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 94, cookies: 95, dns: 96, secrets: 100, attackSurface: 92 },
    highlights: ['Automated HTTPS redirect', 'Strict HSTS preload', 'Clean dependency footprint'],
  },
  {
    domain: 'docker.com',
    slug: 'docker-com',
    name: 'Docker',
    category: 'devtools',
    score: 86,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 84, cookies: 90, dns: 92, secrets: 100, attackSurface: 85 },
    highlights: ['Cloudflare protected', 'No sensitive file leaks', 'HSTS enabled'],
  },
  {
    domain: 'datadog.com',
    slug: 'datadog-com',
    name: 'Datadog',
    category: 'devtools',
    score: 92,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 96, dns: 96, secrets: 100, attackSurface: 91 },
    highlights: ['SOC 2 Type II & FedRAMP alignment', 'Strict cookie isolation', 'DNSSEC validation'],
  },
  {
    domain: 'npmjs.com',
    slug: 'npmjs-com',
    name: 'npm',
    category: 'devtools',
    score: 90,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 90, cookies: 92, dns: 95, secrets: 100, attackSurface: 88 },
    highlights: ['Supply chain security verified', 'Fastly edge delivery', 'Strict 2FA authentication flow'],
  },
  {
    domain: 'postman.com',
    slug: 'postman-com',
    name: 'Postman',
    category: 'devtools',
    score: 88,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 87 },
    highlights: ['API security controls active', 'HSTS preload configured', 'Zero exposed source maps'],
  },

  // 5. E-Commerce & Retail
  {
    domain: 'shopify.com',
    slug: 'shopify-com',
    name: 'Shopify',
    category: 'ecommerce',
    score: 92,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 94, cookies: 95, dns: 96, secrets: 100, attackSurface: 90 },
    highlights: ['PCI DSS Level 1 compliant', 'Hardened cookie prefixes', 'Cloudflare edge protection'],
  },
  {
    domain: 'ebay.com',
    slug: 'ebay-com',
    name: 'eBay',
    category: 'ecommerce',
    score: 76,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 17, warning: 5, failed: 2, total: 24 },
    categoryScores: { tls: 92, headers: 70, cookies: 84, dns: 88, secrets: 100, attackSurface: 75 },
    highlights: ['Complex multi-domain marketplace', 'Permissive script-src on older portals', 'DMARC active'],
  },
  {
    domain: 'etsy.com',
    slug: 'etsy-com',
    name: 'Etsy',
    category: 'ecommerce',
    score: 89,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 88 },
    highlights: ['Strict anti-clickjacking headers', 'Fastly TLS 1.3', 'HSTS preload active'],
  },
  {
    domain: 'walmart.com',
    slug: 'walmart-com',
    name: 'Walmart',
    category: 'ecommerce',
    score: 75,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 17, warning: 5, failed: 2, total: 24 },
    categoryScores: { tls: 94, headers: 70, cookies: 82, dns: 88, secrets: 100, attackSurface: 74 },
    highlights: ['Akamai WAF fronting', 'Heavy third-party analytics footprint', 'Full HTTPS enforcement'],
  },
  {
    domain: 'target.com',
    slug: 'target-com',
    name: 'Target',
    category: 'ecommerce',
    score: 78,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 18, warning: 4, failed: 2, total: 24 },
    categoryScores: { tls: 94, headers: 74, cookies: 85, dns: 90, secrets: 100, attackSurface: 76 },
    highlights: ['HSTS configured', 'Strict cookie security', 'Broad CSP script sources'],
  },
  {
    domain: 'bestbuy.com',
    slug: 'bestbuy-com',
    name: 'Best Buy',
    category: 'ecommerce',
    score: 77,
    grade: 'B',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 17, warning: 5, failed: 2, total: 24 },
    categoryScores: { tls: 92, headers: 72, cookies: 84, dns: 88, secrets: 100, attackSurface: 75 },
    highlights: ['Imperva WAF protection', 'Encrypted TLS 1.3', 'DMARC policy active'],
  },
  {
    domain: 'wayfair.com',
    slug: 'wayfair-com',
    name: 'Wayfair',
    category: 'ecommerce',
    score: 80,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 94, headers: 78, cookies: 86, dns: 90, secrets: 100, attackSurface: 80 },
    highlights: ['Cloudflare CDN security', 'HSTS active', 'Clean secret scanning posture'],
  },

  // 6. Media & Social
  {
    domain: 'spotify.com',
    slug: 'spotify-com',
    name: 'Spotify',
    category: 'media',
    score: 87,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 4, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 86, cookies: 90, dns: 94, secrets: 100, attackSurface: 86 },
    highlights: ['Audio DRM protection architecture', 'HSTS preload active', 'Strict SameSite cookies'],
  },
  {
    domain: 'youtube.com',
    slug: 'youtube-com',
    name: 'YouTube',
    category: 'media',
    score: 62,
    grade: 'C',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 15, warning: 6, failed: 3, total: 24 },
    categoryScores: { tls: 96, headers: 50, cookies: 82, dns: 92, secrets: 100, attackSurface: 75 },
    highlights: ['Google global infrastructure', 'Iframe embedding needs relaxed X-Frame headers', 'HTTPS enforced'],
  },
  {
    domain: 'reddit.com',
    slug: 'reddit-com',
    name: 'Reddit',
    category: 'media',
    score: 82,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 80, cookies: 88, dns: 92, secrets: 100, attackSurface: 82 },
    highlights: ['Fastly edge caching', 'Anti-CSRF tokens on submission forms', 'Strict TLS 1.3'],
  },
  {
    domain: 'discord.com',
    slug: 'discord-com',
    name: 'Discord',
    category: 'media',
    score: 91,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 94, dns: 96, secrets: 100, attackSurface: 90 },
    highlights: ['WebSocket TLS encryption', 'Cloudflare Spectrum DDoS defense', 'Strict CSP directives'],
  },
  {
    domain: 'twitch.tv',
    slug: 'twitch-tv',
    name: 'Twitch',
    category: 'media',
    score: 85,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 84, cookies: 90, dns: 92, secrets: 100, attackSurface: 85 },
    highlights: ['AWS edge video delivery', 'Secure session token entropy', 'Permissions-Policy configured'],
  },
  {
    domain: 'medium.com',
    slug: 'medium-com',
    name: 'Medium',
    category: 'media',
    score: 86,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 20, warning: 3, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 85, cookies: 90, dns: 92, secrets: 100, attackSurface: 85 },
    highlights: ['Subdomain publication isolation', 'DMARC p=reject', 'Zero exposed debug endpoints'],
  },
  {
    domain: 'substack.com',
    slug: 'substack-com',
    name: 'Substack',
    category: 'media',
    score: 88,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 96, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 87 },
    highlights: ['Cloudflare custom domain SSL', 'Strict newsletter email authentication', 'HSTS active'],
  },
  {
    domain: 'linkedin.com',
    slug: 'linkedin-com',
    name: 'LinkedIn',
    category: 'media',
    score: 84,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 19, warning: 4, failed: 1, total: 24 },
    categoryScores: { tls: 96, headers: 82, cookies: 88, dns: 92, secrets: 100, attackSurface: 82 },
    highlights: ['Enterprise identity security', 'Comprehensive DMARC/SPF', 'HSTS preload registration'],
  },

  // 7. AI & Research
  {
    domain: 'openai.com',
    slug: 'openai-com',
    name: 'OpenAI',
    category: 'ai',
    score: 93,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 94, cookies: 96, dns: 96, secrets: 100, attackSurface: 92 },
    highlights: ['Cloudflare Enterprise WAF + Bot Management', 'Strict CSP with strict-dynamic', 'Subdomain takeover protection'],
  },
  {
    domain: 'anthropic.com',
    slug: 'anthropic-com',
    name: 'Anthropic',
    category: 'ai',
    score: 94,
    grade: 'A+',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 23, warning: 1, failed: 0, total: 24 },
    categoryScores: { tls: 100, headers: 95, cookies: 96, dns: 98, secrets: 100, attackSurface: 93 },
    highlights: ['Modern TLS 1.3 & HTTP/3', 'Full HSTS preload suite', 'Hardened cookie prefixes'],
  },
  {
    domain: 'huggingface.co',
    slug: 'huggingface-co',
    name: 'Hugging Face',
    category: 'ai',
    score: 89,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 21, warning: 3, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 88, cookies: 92, dns: 94, secrets: 100, attackSurface: 88 },
    highlights: ['Model hub repository security', 'Strict CSP for Spaces iframes', 'DNSSEC validation'],
  },
  {
    domain: 'perplexity.ai',
    slug: 'perplexity-ai',
    name: 'Perplexity AI',
    category: 'ai',
    score: 92,
    grade: 'A',
    lastScanned: '2026-09-04T18:00:00.000Z',
    summary: { passed: 22, warning: 2, failed: 0, total: 24 },
    categoryScores: { tls: 98, headers: 92, cookies: 96, dns: 96, secrets: 100, attackSurface: 90 },
    highlights: ['Cloudflare edge acceleration & WAF', 'HSTS preload enabled', 'Strict cross-origin isolation'],
  },
];

export function getDomainBySlug(slugOrDomain) {
  if (!slugOrDomain) return null;
  const cleaned = slugOrDomain.toLowerCase().replace(/^www\./, '').trim();
  const slugified = cleaned.replace(/\./g, '-');
  return (
    TOP_DOMAINS.find(
      (d) =>
        d.slug.toLowerCase() === cleaned ||
        d.slug.toLowerCase() === slugified ||
        d.domain.toLowerCase() === cleaned ||
        d.domain.toLowerCase().replace(/\./g, '-') === slugified
    ) || null
  );
}

export function getDomainsByCategory(category) {
  if (!category || category === 'all') return TOP_DOMAINS;
  return TOP_DOMAINS.filter((d) => d.category === category);
}

/**
 * Builds a full scan result object suitable for feeding into
 * CategoryScoreBreakdown and SecurityGraphView for this domain.
 */
export function buildDomainScanResult(domainObj) {
  if (!domainObj) return null;

  return {
    id: `public-report-${domainObj.slug}`,
    url: `https://${domainObj.domain}`,
    score: domainObj.score,
    scannedAt: domainObj.lastScanned,
    summary: domainObj.summary,
    categories: [
      { name: 'Transport & TLS', score: domainObj.categoryScores.tls },
      { name: 'HTTP Security Headers', score: domainObj.categoryScores.headers },
      { name: 'Cookies & CORS', score: domainObj.categoryScores.cookies },
      { name: 'DNS & Email Trust', score: domainObj.categoryScores.dns },
      { name: 'Secrets & Exposure', score: domainObj.categoryScores.secrets },
      { name: 'Attack Surface & Probing', score: domainObj.categoryScores.attackSurface },
    ],
    findings: [
      {
        id: 'f-tls',
        category: 'Transport & TLS',
        title: 'HTTPS Enforcement & Modern TLS',
        severity: 'critical',
        passed: domainObj.categoryScores.tls >= 85,
        description: 'Verifies encrypted transport, cipher strength, and absence of legacy protocols.',
        recommendation: 'Maintain TLS 1.3 with forward secrecy.',
        tier: 'free',
      },
      {
        id: 'f-hsts',
        category: 'Transport & TLS',
        title: 'Strict-Transport-Security (HSTS)',
        severity: 'high',
        passed: domainObj.score >= 75,
        description: 'Forces modern browsers to communicate exclusively over HTTPS.',
        recommendation: 'Configure max-age >= 31536000 with includeSubDomains.',
        tier: 'free',
      },
      {
        id: 'f-csp',
        category: 'HTTP Security Headers',
        title: 'Content Security Policy (CSP)',
        severity: 'critical',
        passed: domainObj.categoryScores.headers >= 85,
        description: 'Restricts sources from which scripts and styles can load to prevent XSS.',
        recommendation: 'Adopt strict-dynamic nonces and eliminate unsafe-inline.',
        tier: 'free',
      },
      {
        id: 'f-frame',
        category: 'HTTP Security Headers',
        title: 'Clickjacking Protection (X-Frame-Options)',
        severity: 'high',
        passed: domainObj.categoryScores.headers >= 70,
        description: 'Guards against clickjacking and UI redressing attacks.',
        recommendation: 'Set X-Frame-Options to DENY or SAMEORIGIN.',
        tier: 'free',
      },
      {
        id: 'f-cookie',
        category: 'Cookies & CORS',
        title: 'Cookie Security Flags (HttpOnly & Secure)',
        severity: 'critical',
        passed: domainObj.categoryScores.cookies >= 85,
        description: 'Protects session tokens from theft via client-side scripts.',
        recommendation: 'Mark all session cookies HttpOnly and Secure.',
        tier: 'free',
      },
      {
        id: 'f-dns',
        category: 'DNS & Email Trust',
        title: 'Email Spoofing Defense (SPF & DMARC)',
        severity: 'high',
        passed: domainObj.categoryScores.dns >= 80,
        description: 'Validates SPF and DMARC enforcement to prevent domain impersonation.',
        recommendation: 'Enforce DMARC p=quarantine or p=reject.',
        tier: 'free',
      },
      {
        id: 'f-secrets',
        category: 'Secrets & Exposure',
        title: 'Public Secrets & Sensitive File Exposure',
        severity: 'critical',
        passed: true,
        description: 'Probes for .env, .git, backups, and exposed credentials in client bundles.',
        recommendation: 'Clean scan: no leaked keys or exposed files found.',
        tier: 'free',
      },
      {
        id: 'f-attack',
        category: 'Attack Surface & Probing',
        title: 'Subdomain Takeover & CNAME Radar',
        severity: 'high',
        passed: domainObj.categoryScores.attackSurface >= 80,
        description: 'Audits DNS records for dangling pointers to abandoned cloud services.',
        recommendation: 'No dangling DNS records detected.',
        tier: 'starter',
      }
    ]
  };
}
